Feature#39/login view
BC-MAY-21-ROR/kata-06-reloj-checador-k06-t01 pull request #42
Opened 2021-07-14 15:28 UTC by jairolan

# Description
What did you implemented/Why did you implemented this:
 - I added a specific scss file for the user login view.
 - I did that so as not to mix the css classes directly in the application.css file.
 - I updated the development.rb file. 
 - That was done so that everyone on the team can log in as an administrator.
 - The login view was designed in its mobile and desktop version. 
   
  ## Screenshots
- Desktop view
![image](https://user-images.githubusercontent.com/45634066/125648956-852fc9d0-2f9c-40cd-8037-119c073c2ac8.png)
- Mobile view
![image](https://user-images.githubusercontent.com/45634066/125649005-98efec32-50c0-429c-86fe-1e56f48a0a1e.png)

2021-07-14 15:38 UTC, oramasangel approved these changes, later dismissed
I like the design for desktop

2021-07-14 16:29 UTC, xFerchoVJ approved these changes, later dismissed
LGTM!

2021-07-14 17:34 UTC, juliocabrera820 commented on reloj-checador/app/javascript/stylesheets/application.scss
> +@import url(devise.scss);
I think you can import the scss file in another way, @Chavin30 is there another way?

2021-07-14 17:35 UTC, juliocabrera820 commented on reloj-checador/app/javascript/stylesheets/devise.scss
> +}
it looks like duplicated code

2021-07-14 17:36 UTC, juliocabrera820 commented on reloj-checador/app/views/devise/sessions/new.html.erb
> +				</div>
keep your indentation and blank lines

2021-07-14 17:37 UTC, juliocabrera820 commented on reloj-checador/app/views/devise/sessions/new.html.erb
> +				<% end %>
keep your indentation and blank lines

2021-07-14 17:38 UTC, juliocabrera820 commented on reloj-checador/app/views/devise/sessions/new.html.erb
> +		</div>
keep your indendation and blank lines

2021-07-14 17:38 UTC, juliocabrera820 commented on reloj-checador/app/views/devise/sessions/new.html.erb
> +      <p>Some text here too.</p> %>
commented-out code must be removed

2021-07-14 17:39 UTC, juliocabrera820 commented on reloj-checador/db/seeds/development.rb
> +User.create name: 'george', email: 'geo@gmail.com', password: '123456', company_id: 1
This code has been added in another branch, so you can remove it

2021-07-14 17:39 UTC, juliocabrera820 requested changes
Nice job ⚡

2021-07-15 16:25 UTC, oramasangel submitted a review, later dismissed

2021-07-15 16:41 UTC, oramasangel approved these changes

2021-07-15 16:42 UTC, juliocabrera820 approved these changes
LGTM

2021-07-15 16:43 UTC, merged